### ISSUE TITLE
bench testing panic

### ISSUE THREAD

**Issue by ccpwcn** [oklog/ulid#95]
# environment
OS: Windows 10
go version: go1.19.5 windows/amd64

# code detail
my code(simple_id.go):
```golang
package simple_id

import (
	"github.com/oklog/ulid/v2"
	"math/rand"
	"sync"
	"time"
)

func SomeIds(count int) (ids []string) {
	ids = make([]string, count, count)
	for i := 0; i < count; i++ {
		ids[i] = ulid.Make().String()
	}
	return ids
}

func SomeIdsParallel(count int) (ids []string) {
	ids = make([]string, count, count)
	var wg sync.WaitGroup
	wg.Add(count)
	entropy := rand.New(rand.NewSource(time.Now().UnixNano()))
	ms := ulid.Timestamp(time.Now())
	for i := 0; i < count; i++ {
		go func(idx int) {
			defer wg.Done()
			if id, err := ulid.New(ms, entropy); err != nil {
				// log.Printf("count %v, idx %v, error %+v", count, idx, err)
				return
			} else {
				ids[idx] = id.String()
			}
		}(i)
	}
	wg.Wait()
	return ids
}
```

my testing code(simple_id_test.go):
```golang
package simple_id

import (
	"testing"
)

func TestSomeIds(t *testing.T) {
	type args struct {
		count int
	}
	tests := []struct {
		name    string
		args    args
		wantIds []string
	}{
		{"3 ids", args{3}, []string{}},
		{"10 ids", args{10}, []string{}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			gotIds := SomeIds(tt.args.count)
			for i, id := range gotIds {
				t.Logf("tests = %v, SomeIds() index = %v, id = %v", tt.name, i, id)
			}
		})
	}
}

func BenchmarkSomeIdsParallel(b *testing.B) {
	type args struct {
		count int
	}
	tests := []struct {
		name    string
		args    args
		wantIds []string
	}{
		{"3 ids", args{3}, []string{}},
		{"10 ids", args{10}, []string{}},
		{"100 ids", args{100}, []string{}},
	}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		for _, tt := range tests {
			b.RunParallel(func(pb *testing.PB) {
				for pb.Next() {
					SomeIdsParallel(tt.args.count)
				}
			})
		}
	}
}
```

# run command an powershell
```powershell
go test -bench="BenchmarkSomeIdsParallel" -benchmem -count=4
```
# The test may succeed or fail
## success:
```plainText
PS E:\code\GoglandProjects\test-any\simple_id> go test -bench="BenchmarkSomeIdsParallel" -benchmem -count=4
goos: windows
goarch: amd64
pkg: test-any/simple_id
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
BenchmarkSomeIdsParallel-8           338          10665132 ns/op        10802996 B/op     157918 allocs/op
BenchmarkSomeIdsParallel-8           360          11162406 ns/op        11505852 B/op     168191 allocs/op
BenchmarkSomeIdsParallel-8           349          10791613 ns/op        11154578 B/op     163056 allocs/op
BenchmarkSomeIdsParallel-8           357          11379811 ns/op        11410379 B/op     166794 allocs/op
PASS
ok      test-any/simple_id      16.881s
```
## fail:
```plainText
PS E:\code\GoglandProjects\test-any\simple_id> go test -bench="BenchmarkSomeIdsParallel" -benchmem -count=4
goos: windows
goarch: amd64
pkg: test-any/simple_id
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
BenchmarkSomeIdsParallel-8           337          11598445 ns/op        10771763 B/op     157458 allocs/op
BenchmarkSomeIdsParallel-8      panic: runtime error: index out of range [-1]                         
goroutine 23572324 [running]:
math/rand.(*rngSource).Uint64(...)
        C:/Program Files/Go/src/math/rand/rng.go:249
math/rand.(*rngSource).Int63(...)
        C:/Program Files/Go/src/math/rand/rng.go:234
math/rand.read({0xc0006ad386, 0xa, 0x78a5cd?}, {0x8eea78?, 0xc00091e000?}, 0xc0000b7e50, 0xc0000b7e58)
        C:/Program Files/Go/src/math/rand/rand.go:274 +0x176
math/rand.(*Rand).Read(0xc0001e04e0?, {0xc0006ad386?, 0x78b4dd?, 0x89f940?})
        C:/Program Files/Go/src/math/rand/rand.go:264 +0x65
io.ReadAtLeast({0x8ee680, 0xc0000b7e30}, {0xc0006ad386, 0xa, 0xa}, 0xa)
        C:/Program Files/Go/src/io/io.go:332 +0x9a
io.ReadFull(...)
        C:/Program Files/Go/src/io/io.go:351
github.com/oklog/ulid/v2.New(0x1862f0ab7fa, {0x8ee680?, 0xc0000b7e30})
        C:/Users/lidawei/go/pkg/mod/github.com/oklog/ulid/v2@v2.1.0/ulid.go:109 +0x11c
test-any/simple_id.SomeIdsParallel.func1(0x2)
        E:/code/GoglandProjects/test-any/simple_id/simple_id.go:27 +0x9b
created by test-any/simple_id.SomeIdsParallel
        E:/code/GoglandProjects/test-any/simple_id/simple_id.go:25 +0x270
exit status 2
FAIL    test-any/simple_id      7.049s
```

**Comment by peterbourgon** [comment]
Your SomeIdsParallel creates a single math/rand.Source of entropy, which is used by multiple goroutines.

```go
func SomeIdsParallel(count int) (ids []string) {
	ids = make([]string, count, count)
	var wg sync.WaitGroup
	wg.Add(count)
	entropy := rand.New(rand.NewSource(time.Now().UnixNano())) // <---
	ms := ulid.Timestamp(time.Now())
	for i := 0; i < count; i++ {
		go func(idx int) { // <---
			defer wg.Done()
			if id, err := ulid.New(ms, entropy); err != nil { // <---
				// log.Printf("count %v, idx %v, error %+v", count, idx, err)
				return
```

But you can't do that.

> A Source is not safe for concurrent use by multiple goroutines.

https://pkg.go.dev/math/rand#Source

Check [the Usage section of the README](https://pkg.go.dev/github.com/oklog/ulid/v2#readme-usage) for information about safe concurrent entropy sources.

**Comment by ccpwcn** [comment]
thanks
